"""empty message

Revision ID: d69157d82645
Revises: e3365f9380ea
Create Date: 2020-04-02 18:53:20.439664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd69157d82645'
down_revision = 'e3365f9380ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'todo_list',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'todo_list',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
